### ISSUE TITLE
Question : themes

### ISSUE THREAD

**Issue by noraj** [Pcrab/hexo-highlight-shiki#11]
Which with themes does it work?

**Comment by Pcrab** [comment]
This plugin uses shiki to highlight code, so I believe you can find all available themes [here](https://unpkg.com/browse/shiki@0.14.7/themes/).

Be aware that this plugin depends on an old version of shiki, because shiki v1.0.0+ only supports esm.

**Comment by noraj** [comment]
I'm sorry my question was unclear, I was asking with which hexo themes (not which shiki themes). Because I tested this plugin but it wasn't working for me using a custom version of [hexo-theme-hueman](https://github.com/ppoffice/hexo-theme-hueman). So in the end I tried [hexo-shiki-plugin](https://github.com/nova1751/hexo-shiki-plugin) instead of this plugin, that was working with my hexo theme because it injects CSS and is theme independent.
Since hexo-highlight-shiki seem to not inject CSS it means the CSS has to be brought by the hexo theme then, am I right?

**Comment by Pcrab** [comment]
I've test it with latest hexo and [hexo-theme-hueman](https://github.com/ppoffice/hexo-theme-hueman), and the plugin works as expected. This plugin should be theme independent and it inlines all the style it needs.

Maybe you are using a hexo version less than 7? Can you provide a minimal reproducible example?

![image](https://github.com/user-attachments/assets/f6f3b106-97e1-42fa-8c9b-cac93df60370)
![image](https://github.com/user-attachments/assets/45bffe35-9f7e-4fee-af43-a04186e0a79a)

**Comment by noraj** [comment]
Hexo 7+ but it was maybe my custom modifications or additional CSS that was conflicting.
